apiVersion: apps/v1
kind: Deployment
metadata:
  name: revhire-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: revhire-app
  template:
    metadata:
      labels:
        app: revhire-app
    spec:
      containers:
      - name: rev-hire-container
        image: nikhilkothale17/revhire_pro:latest
        ports:
        - containerPort: 8000
